### ISSUE TITLE
Test skipped due to failure in previous step

### ISSUE THREAD

**Issue by ylavoie** [pherkin/test-bdd-cucumber-perl#123]
In a feature test with examples, failure in one step should only skip remaining steps of the current example.
Currently, a failure in an example skip all other examples.

**Comment by pjlsergeant** [comment]
I don't think that's accurate - specifically I don't think that's how
Cucumber works

**Comment by ylavoie** [comment]
Coming soon, see https://github.com/cucumber/cucumber/issues/79

**Comment by pjlsergeant** [comment]
Heh, this will invalidate most of my MSc dissertation :’)

They are proposing something slightly different there, which I like, which
is the idea that a step can be marked as being allowed to soft-fail. If you
want to implement that, I’ll accept it with open arms. I have a few ideas
on how to do that nicely if that’s something you want to do.

-P

**Comment by ylavoie** [comment]
I do like both. So yes, I'd like to read your ideas about that.
My original goal, and I've seen it shared in many cucumber forums, was to consider examples in outlines as independent scenarios, so the failure of one shouldn't have any impact on others. I will certainly add my voice to the chorus there too.
Soft-fail steps add another nice twist that could give the same effect for outlines and examples.

**Comment by ehuelsmann** [comment]
It's actually *not* coming soon. The referenced issue has been closed without resolution.

**Comment by ehuelsmann** [comment]
I think that if we switch to cucumber/cucumber's gherkin-perl (aka Gherkin module on CPAN) after cucumber/cucumber#694 has been merged, this problem solves itself: In the pickle output each **scenario** (not scenario outline) is its own testing unit, which means that failure of one "example" won't mean automatic failure of all examples.

**Comment by ehuelsmann** [comment]
The conclusion on the referred thread is that the community desperately wants it (the soft assertions), but nobody has enough skills to implement it for all backends. So, the issue ended up being closed.

**Comment by ehuelsmann** [comment]
Just verified in the Cucumber committers Slack channel: each expanded scenario should be treated as a completely separate scenario. The scenario outline is only syntactic sugar to the definition of multiple scenarios.

That means that - as I understand @ylavoie's request - we should implement as he requested.
