### ISSUE TITLE
Are table placeholders valid Cucumber?

### ISSUE THREAD

**Issue by kivilahtio** [pherkin/test-bdd-cucumber-perl#133]
Hi!
I have the following step:

```
  Given a set of letter templates
   | module      | code  | branchcode | name    | is_html | title  | message_transport_types | content |
   | circulation | ODUE1 |            | Notice1 |         | Title1 | print, email, sms       | <item>Barcode: <<items.barcode>>, bring it back!</item> |
   | circulation | ODUE2 |            | Notice2 |         | Title2 | print, email, sms       | <item>Barcode: <<items.barcode>></item> |
   | circulation | ODUE3 |            | Notice3 |         | Title3 | print, email, sms       | <item>Barcode: <<items.barcode>>, bring back!</item> |
```

This creates XML:ish templates that are needed to format output. Testing this output is the point of this feature.
How should the <> less-than/greater-than characters be escaped?
Where in the Gherkin/Cucumber documentation the table data columns are evaluated for placeholders?

The error thrown is:
```
-- Parse Error --

 No mapping to placeholder <item>
  at [features/Overdues/3.getItemsFromOldOverdues.feature] line 39
  thrown by: [/usr/local/share/perl/5.26.1/Test/BDD/Cucumber/Executor.pm] line 382
```

I presume disabling:
https://metacpan.org/source/SARGIE/Test-BDD-Cucumber-0.56/lib/Test/BDD/Cucumber/Executor.pm#L316
Would solve the issue.

The big question is, what is the standards-compliant way of solving this problem?

**Comment by ehuelsmann** [comment]
@kivilahtio thank you for your question and sorry for the long time without a response. Yes, table placeholders are valid Gherkin (See this test case in the canonical Gherkin test suite: https://github.com/cucumber/cucumber/blob/master/gherkin/testdata/good/example_tokens_everywhere.feature).

With this sorted, I think we're doing this little thing correctly -- among all the things we don't....
