### ISSUE TITLE
Dependency declaration insufficient

### ISSUE THREAD

**Issue by andk** [pherkin/test-bdd-cucumber-perl#157]
Hi Erik, I just found this fail report of my smoker: http://www.cpantesters.org/cpan/report/79fc321e-dc35-11e9-b177-25c8fc1a8ddd

It reveals that Test2::API 1.302086 did not have a pass() method. The declared version number of 1.302084 is apparently not sufficient.

**Comment by ehuelsmann** [comment]
Thanks. Looking at the changes again, I think it should have been 1.302087, which is documented to add pass and fail events.

**Comment by andk** [comment]
It may be worth trying it out. I just did and got a different fail.

**Comment by ehuelsmann** [comment]
Locally, I get the same error with 86 but no errors with 87. I'll update the dependency to 87.
