### ISSUE TITLE
Getting error trying to use the module Test::BDD::Cucumber::StepFile

### ISSUE THREAD

**Issue by FernandoOjeda** [pherkin/test-bdd-cucumber-perl#165]
use Test::BDD::Cucumber::StepFile;

**Output:**
Modification of a read-only value attempted at C:/Dwimperl/perl/lib/Exporter.pm line 66, <DATA> line 3514.
BEGIN failed--compilation aborted at C:/steps.pl line 10, <DATA> line 3514.

**Comment by ehuelsmann** [comment]
Thanks for reporting!

Can you provide a bit more detail? Like:

* Which version of Test::BDD::Cucumber are you using?
* Which Perl version are you using?
* What is the exact command you're running which causes the above output?

Thanks!

**Comment by FernandoOjeda** [comment]
Sorry for the delay:
Cucumber version:
Test-BDD-Cucumber-0.72
Version Perl:
perl 5, version 12, subversion 3 (v5.12.3) built for MSWin32-x86-multi-thread.

The error was when I run my script using this module:
I am using this modules:
`#!/usr/bin/perl

#!perl

use strict;
use warnings;
use Test::More;

use Test2::Bundle::More;

use Test::BDD::Cucumber::StepFile;`

And the error came from this module Test::BDD::Cucumber::StepFile

Thanks.

**Comment by ehuelsmann** [comment]
Fixed and uploaded as version 0.73.
