### ISSUE TITLE
Failure exit codes from pherkin does not work

### ISSUE THREAD

**Issue by tomas-zemres** [pherkin/test-bdd-cucumber-perl#172]
It looks like this condition is not correct

https://github.com/pherkin/test-bdd-cucumber-perl/blob/79cbee55551def5f592816d7592785c073eab180/lib/App/pherkin.pm#L128

because **$result** is not a string, but instance of **Test::BDD::Cucumber::Model::Result**

**Comment by tomas-zemres** [comment]
There should be
`my $result = $harness->result->result;` instead of `my $result = $harness->result;`

in https://github.com/pherkin/test-bdd-cucumber-perl/blob/79cbee55551def5f592816d7592785c073eab180/lib/App/pherkin.pm#L127

**Comment by ehuelsmann** [comment]
Thanks for the report! It's fixed in the repository. I'll have a look at releasing and update here when it's released on CPAN.

**Comment by ehuelsmann** [comment]
Released on CPAN.
