### ISSUE TITLE
Running pherkin when the basic.feature file is empty gives warnings

### ISSUE THREAD

**Issue by szabgab** [pherkin/test-bdd-cucumber-perl#178]
```
Use of uninitialized value in concatenation (.) or string at /home/gabor/perl5/lib/perl5/Test/BDD/Cucumber/Harness/TermColor.pm line 136.
Use of uninitialized value in concatenation (.) or string at /home/gabor/perl5/lib/perl5/Test/BDD/Cucumber/Harness/TermColor.pm line 136.
```

If I add `Feature: Hello World` to the file then warnings are gone.

**Comment by ehuelsmann** [comment]
BTW, if you want to discuss interactively with me, I'm around in the Pherkin chat channel at https://app.element.io/#/room/#pjlsergeant_test-bdd-cucumber-perl:gitter.im ; I'm also in #perl on freenode, btw.
