### ISSUE TITLE
Is it possible detect conflicts in step-definition?

### ISSUE THREAD

**Issue by tomas-zemres** [pherkin/test-bdd-cucumber-perl#90]
Hello,

Is it possible detect (or raise error) if one step matches multiple subroutines in *_steps.pl files?

**Comment by pjlsergeant** [comment]
It would be, and it would also be possible to check each step will match, which is another similar feature request. Perhaps a `check` flag of some type to Pherkin is the way forward here?

**Comment by pjlsergeant** [comment]
I would very much like to get this implemented

**Comment by ehuelsmann** [comment]
@tomas-zemres this functionality has now been implemented and will be released (later today) in version 0.60. See `--matching` in the help output of `bin/pherkin` for that version.

**Comment by ehuelsmann** [comment]
Oh. I forget to mention that the code either throws an error at the duplicate match (and stops processing) or warns on every one.

Also, the output will list *exactly* which steps are matching: step regex as well as location where the step was defined.
