### ISSUE TITLE
Step-debugging problem: "Bizarre copy of ARRAY" replaces stacktrace

### ISSUE THREAD

**Issue by ehuelsmann** [pherkin/test-bdd-cucumber-perl#92]
When I run the tests through `pherkin` (which I prefer over `prove`, because in our setup then I can control better which tests are being run), I'm getting the following output. Notice that there's no stacktrace whatsoever.

``` gherkin
    Scenario: Viewing setup.pl
      Given a user named "Admin" with a password "a6m1n"
      When I navigate to the setup login page
        step defined at t/66-cucumber/01-basic/login.feature line 12.
        ok 1 - Starting to execute step: I navigate to the setup login page
        not ok 2 - Test compiled
        #   Failed test 'Test compiled'
        #   at /home/ehuelsmann/perl5/lib/perl5/Test/BDD/Cucumber/Executor.pm line 445.
        # Bizarre copy of ARRAY in list assignment at /home/ehuelsmann/perl5/lib/perl5/Devel/StackTrace.pm line 61.
        1..2
```

When I run the same test script through `prove`, I get the following output:

```
#   Failed test '         When I navigate to the setup login page'
#   at /home/ehuelsmann/perl5/lib/perl5/Test/BDD/Cucumber/Harness/TestBuilder.pm line 87.
#   in step at t/66-cucumber/01-basic/login.feature line 12.
# ok 1 - Starting to execute step: I navigate to the setup login page
# not ok 2 - Test compiled
# 
# #   Failed test 'Test compiled'
# #   at /home/ehuelsmann/perl5/lib/perl5/Test/BDD/Cucumber/Executor.pm line 445.
# # Cannot assign a value to a read-only accessor at reader Weasel::Session::page (defined at /home/ehuelsmann/perl5/lib/perl5/Weasel/Session.pm line 87) line 3
# #     Weasel::Session::page('Weasel::Session=HASH(0x8cefb10)', 'PageObject::Setup::Login=HASH(0x9827620)') called at t/lib/PageObject.pm line 24
# #     PageObject::open('PageObject::Setup::Login', 'driver', 'Weasel::Session=HASH(0x8cefb10)') called at t/66-cucumber/01-basic/step_definitions/pageobject_steps.pl line 63
# #     Test::BDD::Cucumber::StepFile::__ANON__('Test::BDD::Cucumber::StepContext=HASH(0x9e3a058)') called at /home/ehuelsmann/perl5/lib/perl5/Test/BDD/Cucumber/Executor.pm line 535
# #     eval {...} at /home/ehuelsmann/perl5/lib/perl5/Test/BDD/Cucumber/Executor.pm line 535
# #     Test::BDD::Cucumber::Executor::dispatch('Test::BDD::Cucumber::Executor=HASH(0x9652328)', 'Test::BDD::Cucumber::StepContext=HASH(0x9e3a058)', 'ARRAY(0x9839048)', 0, 0) called at /home/ehuelsmann/perl5/lib/perl5/Test/BDD/Cucumber/Executor.pm line 445
# #     Test::BDD::Cucumber::Executor::find_and_dispatch('Test::BDD::Cucumber::Executor=HASH(0x9652328)', 'Test::BDD::Cucumber::StepContext=HASH(0x9e3a058)', 0, 0) called at /home/ehuelsmann/perl5/lib/perl5/Test/BDD/Cucumber/Executor.pm line 336
# #     Test::BDD::Cucumber::Executor::execute_scenario('Test::BDD::Cucumber::Executor=HASH(0x9652328)', 'HASH(0x9656c10)') called at /home/ehuelsmann/perl5/lib/perl5/Test/BDD/Cucumber/Executor.pm line 178
# #     Test::BDD::Cucumber::Executor::execute('Test::BDD::Cucumber::Executor=HASH(0x9652328)', 'Test::BDD::Cucumber::Model::Feature=HASH(0x9853048)', 'Test::BDD::Cucumber::Harness::TestBuilder=HASH(0x9651f20)') called at t/66-cucumber.t line 66
#1..2
```

Which **does** have a full stacktrace and shows the actual error that's happening. (Now, I'm not even after the full stack trace, which would be nice, but I need to have the error, of course...)

**Comment by ehuelsmann** [comment]
Note that I'm using ```Carp``` and/or ```Carp::Always``` to produce the full stacktrace.

**Comment by pjlsergeant** [comment]
What versions of `Devel::StackTrace`, `Carp`, and `Carp::Always` are you running?

**Comment by ehuelsmann** [comment]
I'm using these versions:

| Module | Version |
| -------|------:|
| Carp | 1.3301 |
| Carp::Always | 0.13 |
| Devel::StackTrace | 2.01 |

**Comment by ylavoie** [comment]
This is notorious in Perl version and has been there for a long time. Perl 5.24 says `Perl detected an attempt to copy an internal value that is not copiable.` It is present in various  `Devel::StackTrace`, `Carp`, and `Carp::Always` and is usually related/showned by `DB::args` calls.

**Comment by emarcotte** [comment]
Found this, and an old RT, with a plea to make `Carp` not crash at the end here: https://rt.perl.org/Public/Bug/Display.html?id=52610 

Applying the "unknown" trick ends up showing this call line at the bottom of the stacktrace:

```
        #       App::pherkin::run(''App::pherkin=HASH(0x20c9fd8)'', ''HASH(0x517dc68)'', 'unknown', ''HASH(0x20ca3c8)'') called at /home/emarcotte/emarcotte-dev/prod/local/5.16/bin/pherkin line 173
```

I tried playing with the things messing with `@ARGV` but it didn't seem to make any difference.

**Comment by ehuelsmann** [comment]
Apparently, this is a long standing issue with all versions of Perl. Not a pherkin issue by and of itself. (At best it's a Carp issue...) The differences in the stack apparently cause this not to be a problem with `prove`.

What *might* be a solution is to capture a reference to each of the values in the @ARGV array by assigning @ARGV to a `my` variable on line 172 in `bin/pherkin`.

**Comment by ehuelsmann** [comment]
@emarcotte Do you still have a setup to reproduce this problem? I lost mine. 

If you don't either, I think we need to close this issue until someone does.

**Comment by emarcotte** [comment]
Theres almost no chance I still have this.

**Comment by ehuelsmann** [comment]
Ok. Thanks for responding. I'll close this and work on it again when it pops up.
